#' Print summary information on a \code{tvcure.object}.
#'
#' @description
#' Print summary information on a \code{tvcure.object} generated by \code{\link{tvcure}}.
#'
#' @usage \method{print}{tvcure}(x, ci.level=.95,expEst=TRUE,digits=3,eps.Pvalue=0.001,...)
#'
#' @param x an object of class \code{\link{tvcure.object}}.
#' @param ci.level (optional) nominal level for the plotted pointwise credible intervals (default: .95).
#' @param expEst (optional) logical indicating if the exponential of the regression parameter estimates should also be provided (with their confidence interval) (default: TRUE).
#' @param digits number of digits when reporting parameter estimates (default: 3).
#' @param eps.Pvalue Value below which a P-value is just reported to be less than \code{eps.Pvalue} (defaut: 0.001).
#' @param ... additional generic printing arguments.
#'
#' @details Provides summary measures on the estimation of the regression parameters and additive terms
#' in the tvcure model corresponding to a \code{\link{tvcure.object}} generated by \code{\link{tvcure}}.
#'
#' @return No returned value (just printed summary).
#'
#' @author Philippe Lambert \email{p.lambert@uliege.be}
#' @references Lambert, P. and Kreyenfeld, M. (2024). Exogenous time-varying covariates in double additive cure survival model
#' with application to fertility. \emph{Journal of the Royal Statistical Society, Series A}, under review.
#'
#' @examples
#' require(tvcure)
#' ## Simulated data generation
#' beta = c(beta0=.4, beta1=-.2, beta2=.15) ; gam = c(gam1=.2, gam2=.2)
#' data = simulateTVcureData(n=500, seed=123, beta=beta, gam=gam,
#'                           RC.dist="exponential",mu.cens=550)$rawdata
#' ## TVcure model fitting
#' tau.0 = 2.7 ; lambda1.0 = c(40,15) ; lambda2.0 = c(25,70) ## Optional
#' model = tvcure(~z1+z2+s(x1)+s(x2), ~z3+z4+s(x3)+s(x4), data=data,
#'                tau.0=tau.0, lambda1.0=lambda1.0, lambda2.0=lambda2.0)
#' print(model)
#'
#' @seealso \code{\link{tvcure}}, \code{\link{tvcure.object}}, \code{\link{plot.tvcure}}
#'
#' @export
#'
print.tvcure <- function(x,ci.level=.95,expEst=TRUE,digits=3,eps.Pvalue=0.001,...){
    obj = x
    printMat1 = function(mat) printCoefmat(mat, digits=digits,eps.Pvalue=eps.Pvalue,
                                           cs.ind=1:4,tst.ind=5,
                                           P.values=TRUE,has.Pvalue=TRUE,
                                           signif.legend=FALSE,...)
    printMat2 = function(mat) printCoefmat(mat, digits=digits,eps.Pvalue=eps.Pvalue,
                                           P.values=TRUE,has.Pvalue=TRUE,
                                           signif.legend=FALSE,...)
    printMat3 = function(mat) printCoefmat(mat, digits=digits,eps.Pvalue=eps.Pvalue,
                                           cs.ind=1,tst.ind=c(2,4),
                                           P.values=TRUE,has.Pvalue=TRUE,
                                           signif.legend=FALSE,...)
    cat("\nCall:\n")
    print(x$call)
    cat("\n")
    ##
    cat(">> log(theta(x)) - Long-term survival (Quantum) <<\n")
    cat("Formula:",deparse(obj$formula1),"\n")
    nfixed1 = obj$regr1$nfixed
    cat("\nParametric coefficients:\n")
    mat = obj$fit$beta[1:nfixed1,,drop=FALSE]
    printMat1(mat)
    ##
    if (expEst & nfixed1 > 1){ ## Print exp(est)
        cat("\n")
        ## mat = with(obj$fit, cbind("exp(est)"=exp(beta[,"est"]),
        ##                           low=exp(beta[,"low"]),
        ##                           up=exp(beta[,"up"]),
        ##                           "exp(-est)"=exp(-beta[,"est"]),
        ##                           low=exp(-beta[,"up"]),
        ##                           up=exp(-beta[,"low"]),
        ##                           Pval=beta[,"Pval"]))
        mat = with(obj$fit, cbind("exp(est)"=exp(beta[,"est"]),
                                  "exp(-est)"=exp(-beta[,"est"]),
                                  low=exp(beta[,"low"]),
                                  up=exp(beta[,"up"]),
                                  Pval=beta[,"Pval"]))
        printMat2(mat[2:nfixed1,,drop=FALSE])
    }
    ##
    if (obj$regr1$J > 0){
        cat("\nApproximate significance of smooth terms (using Wood's <Tr> or Chi2):\n")
        printMat3(cbind(obj$fit$ED1.Tr,obj$fit$ED1.Chi2[,-1,drop=FALSE]))
    }
    ##
    cat("\n\n>> eta(x) - Short-term survival (Timing) <<\n")
    ## switch(obj$baseline,
    ##        "S0" = {
    ##            cat("S.p(t|x) = exp{-theta(x) F(t|x)}  where  1-F(t|x) = S(t|x) = S.0(t)^exp(eta(x))\n")
    ##        },
    ##        "F0" = {
    ##            cat("S.p(t|x) = exp{-theta(x) F(t|x)}  where  F(t|x) = F.0(t)^exp(eta(x))\n")
    ##        }
    ## )
    cat("Formula:",deparse(obj$formula2),"\n")
    nfixed2 = obj$regr2$nfixed
    cat("\nParametric coefficients:\n")
    if (nfixed2 == 0){
        cat("No intercept or linear term \n")
    } else {
        printMat1(obj$fit$gamma[1:obj$regr2$nfixed,,drop=FALSE])
    }
    ##
    if (expEst & nfixed2 > 0){ ## Print exp(est)
        cat("\n")
        ## mat = with(obj$fit, cbind("exp(est)"=exp(gamma[,"est"]),
        ##                           low=exp(gamma[,"low"]),
        ##                           up=exp(gamma[,"up"]),
        ##                           "exp(-est)"=exp(-gamma[,"est"]),
        ##                           low=exp(-gamma[,"up"]),
        ##                           up=exp(-gamma[,"low"]),
        ##                           Pval=gamma[,"Pval"]) )
        mat = with(obj$fit, cbind("exp(est)"=exp(gamma[,"est"]),
                                  "exp(-est)"=exp(-gamma[,"est"]),
                                  low=exp(gamma[,"low"]),
                                  up=exp(gamma[,"up"]),
                                  Pval=gamma[,"Pval"]) )
        printMat2(mat[1:nfixed2,,drop=FALSE])
    }
    ##
    if (obj$regr2$J > 0){
        cat("\nApproximate significance of smooth terms (using Wood's <Tr> or Chi2):\n")
        printMat3(cbind(obj$fit$ED2.Tr,obj$fit$ED2.Chi2[,-1,drop=FALSE]))
    }
    ##
    cat("\n------------------------------------------------------------------------\n")
    cat(" logEvid:",round(obj$fit$levidence,2),
        "  Dev:",round(obj$fit$dev,2),
        "  AIC:",obj$fit$AIC,
        "  BIC:",obj$fit$BIC,
        "\n")
    cat(" edf: ",round(obj$fit$ED.tot,2),
        "  nobs: ",obj$fit$nobs,
        "  n: ",obj$fit$n," (units)",
        "  d: ",obj$fit$d," (events)",
        "\n",sep="")
    cat(" Elapsed time: ",round(obj$fit$elapsed.time,1)," seconds  (",obj$fit$iter," iterations)\n",sep="")
    cat("------------------------------------------------------------------------\n")
}
